apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: shareify-item-service
  labels:
    app: shareify-item-service
spec:
  serviceName: "shareify-item-service"
  replicas: 1
  selector:
    matchLabels:
      app: shareify-item-service
  template:
    metadata:
      labels:
        app: shareify-item-service
    spec:
      containers:
        - name: item-service
          image: mvnsakash/shareify-item-service:v1.1.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: JWT_SECRET
              value: "shareify-secret-key-2024"
            - name: DATABASE_PATH
              value: "/data/items.db"
            - name: INVENTORY_SERVICE_URL
              value: "http://shareify-inventory-service:8000"
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "csi-standard"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: shareify-item-service
  labels:
    app: shareify-item-service
spec:
  type: ClusterIP
  selector:
    app: shareify-item-service
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
