apiVersion: apps/v1
kind: Deployment
metadata:
  name: shareify-{{ .Values.frontend.name }}
  labels:
    app: shareify-{{ .Values.frontend.name }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  strategy:
    {{- toYaml .Values.frontend.strategy | nindent 4 }}
  selector:
    matchLabels:
      app: shareify-{{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        app: shareify-{{ .Values.frontend.name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.global.dockerUsername }}/shareify-{{ .Values.frontend.name }}:{{ .Values.frontend.imageTag | default .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.backendDefaults.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: shareify-{{ .Values.frontend.name }}
  labels:
    app: shareify-{{ .Values.frontend.name }}
spec:
  type: ClusterIP
  selector:
    app: shareify-{{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
